spring:  datasource:    url: jdbc:mysql://localhost:3306/dmzjbot?characterEncoding=UTF-8&serverTimezone=UTC    username: root    password: 123456    driver-class-name: com.mysql.cj.jdbc.Driver
coolq: 
  base: 
    home: D:\Software\Coolq\酷Q Air  manager: 1339633536  bot: 1023915086  mem:     iniCoin: 20    coinIncr: -6    iniFavorability: 0    favorabilityIncr: 1
